# Generated by Django 4.2.6 on 2023-11-10 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
                ('email', models.EmailField(max_length=50, verbose_name='Эл.почта')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'клиента',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата заказа')),
                ('type_cleaning', models.CharField(max_length=50, verbose_name='Вариант уборки')),
                ('status', models.CharField(max_length=50, verbose_name='Статус заказа')),
                ('price', models.IntegerField(verbose_name='Цена услуги')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clients')),
            ],
            options={
                'verbose_name': 'закаказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
