# Generated by Django 4.2.6 on 2023-10-04 20:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=50, verbose_name='Эл.почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=50, region=None, verbose_name='Телефон')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиент',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surename', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=50, verbose_name='Эл.почта')),
                ('phone', models.TextField(max_length=11, verbose_name='Телефон')),
                ('review', models.TextField(verbose_name='Напишите отзыв здесь')),
                ('recommendation', models.CharField(max_length=5)),
                ('suggestion', models.TextField(verbose_name='Что бы вы изменили в работе?')),
            ],
            options={
                'verbose_name': 'Рекоментация',
                'verbose_name_plural': 'Рекомендации',
            },
        ),
    ]
