# Generated by Django 4.2.6 on 2023-11-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_orders_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('price', models.IntegerField(max_length=20, verbose_name='Цена')),
                ('pics', models.ImageField(upload_to='', verbose_name='Картинка')),
            ],
        ),
    ]
