# Generated by Django 4.2.6 on 2023-11-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
